### ISSUE TITLE
Analyzer fails to build container

### ISSUE THREAD

**Issue by jeremy-marcus** [microsoft/CSharpCodeAnalyzer#14]
When trying to use this action I get the following:

```
Build container for action use: '/home/runner/work/_actions/microsoft/CSharpCodeAnalyzer/v0.1-beta/Dockerfile'.
/usr/bin/docker build -t 3888d3:59e75f2b20424588af762728dae4f8b8 -f "/home/runner/work/_actions/microsoft/CSharpCodeAnalyzer/v0.1-beta/Dockerfile" "/home/runner/work/_actions/microsoft/CSharpCodeAnalyzer/v0.1-beta"
pull access denied for xinshi/csharpcodeanalyzer, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Sending build context to Docker daemon  60.93kB

Step 1/3 : FROM xinshi/csharpcodeanalyzer:3721994-g1f43701f1f1b62a54e21600c4b3bf788082d64c2
##[warning]Docker build failed with exit code 1, back off 7.787 seconds before retry.
/usr/bin/docker build -t 3888d3:59e75f2b20424588af762728dae4f8b8 -f "/home/runner/work/_actions/microsoft/CSharpCodeAnalyzer/v0.1-beta/Dockerfile" "/home/runner/work/_actions/microsoft/CSharpCodeAnalyzer/v0.1-beta"
Sending build context to Docker daemon  60.93kB

pull access denied for xinshi/csharpcodeanalyzer, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Step 1/3 : FROM xinshi/csharpcodeanalyzer:3721994-g1f43701f1f1b62a54e21600c4b3bf788082d64c2
##[warning]Docker build failed with exit code 1, back off 9.625 seconds before retry.
/usr/bin/docker build -t 3888d3:59e75f2b20424588af762728dae4f8b8 -f "/home/runner/work/_actions/microsoft/CSharpCodeAnalyzer/v0.1-beta/Dockerfile" "/home/runner/work/_actions/microsoft/CSharpCodeAnalyzer/v0.1-beta"
Sending build context to Docker daemon  60.93kB

Step 1/3 : FROM xinshi/csharpcodeanalyzer:3721994-g1f43701f1f1b62a54e21600c4b3bf788082d64c2
pull access denied for xinshi/csharpcodeanalyzer, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
##[error]Docker build failed with exit code 1
```

**Comment by xi-liu-ds** [comment]
Thanks for your interested in C# Code Analyzer GitHub Action. For now we temporarily pulled our GitHub Action for maintenance. We will keep you posted when it is online again. Thanks again.

**Comment by RubenMateus** [comment]
Having the same issue. can you at least give us a timeline? @xi-liu-ds

**Comment by xi-liu-ds** [comment]
> Having the same issue. can you at least give us a timeline? @xi-liu-ds

We will try to get it back online by EOW. I will keep you informed. 

Thanks for your interest :-)

**Comment by xi-liu-ds** [comment]
Hi, 

We are excited to let you know we are pushing for full open sourcing and currently going through internal reviews. C# Code Analyzer GitHub Action, together with the docker container, will be part of the OSS release. Sorry for the inconvenience. We are trying our best to get it out ASAP. Thanks!

**Comment by andrewvaughanj** [comment]
@xi-liu-ds does this also include your modifications to Infer? Are you going to try and get these merged into the upstream project?

**Comment by xi-liu-ds** [comment]
> @xi-liu-ds does this also include your modifications to Infer? Are you going to try and get these merged into the upstream project?

Yes

**Comment by xi-liu-ds** [comment]
Hi all,

I am excited to share that C# Code Analyzer is live again! Meanwhile, we open sourced its core: Infer#!

•	Infer# open source: https://github.com/microsoft/infersharp.
•	GitHub Action: https://github.com/marketplace/actions/c-code-analyzer

Thank you all for your interests!
