### ISSUE TITLE
README.md contains a broken link to the InferSharp source code

### ISSUE THREAD

**Issue by andrewvaughanj** [microsoft/CSharpCodeAnalyzer#21]
## Issue

Commit b6e7e9114cd586daae75618dc306bb347f570e21 introduced a link to [https://github.com/microsoft/infersharp](https://github.com/microsoft/infersharp) to obtain the InferSharp source code.

However, this repo either doesn't yet exist, or is private -- either way, you get a 404.

**Comment by matjin** [comment]
@andrewvaughanj Yes -- the link points to the source code of our pipeline, which we are in the final stretch of open sourcing. We are currently in the final stretch of validation, and the repo will be made public very soon.

**Comment by andrewvaughanj** [comment]
@matjin sounds great!

**Comment by matjin** [comment]
@andrewvaughanj the code is live on Github! Thank you for your patience.

**Comment by andrewvaughanj** [comment]
💥
